name: Frontend tests

on:
  pull_request:

permissions: {}

jobs:
  detect-changes:
    name: Detect frontend changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      changed: ${{ steps.detect-changes.outputs.frontend }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          fetch-depth: 2
      - name: Detect changes
        id: detect-changes
        uses: ./.github/actions/change-detection
        with:
          self: .github/workflows/pr-frontend-unit-tests.yml

  frontend-unit-tests:
    needs:
      - detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    runs-on: ubuntu-latest
    name: Unit tests (${{ matrix.shard }} / ${{ matrix.total }})
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5, 6, 7, 8]
        total: [8]
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Yarn install
        run: yarn install --immutable
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
          CYPRESS_INSTALL_BINARY: 0
      - name: Run unit tests
        run: yarn run test:ci
        env:
          TEST_MAX_WORKERS: 4
          TEST_SHARD: ${{ matrix.shard }}
          TEST_SHARD_TOTAL: ${{ matrix.total }}

  frontend-decoupled-plugin-tests:
    needs:
      - detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    runs-on: ubuntu-latest
    name: Decoupled plugin tests
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Yarn install
        run: yarn install --immutable
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
          CYPRESS_INSTALL_BINARY: 0
      - run: yarn run plugin:test:ci

  frontend-packages-unit-tests:
    needs:
      - detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    runs-on: ubuntu-latest
    name: Packages unit tests
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Yarn install
        run: yarn install --immutable
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
          CYPRESS_INSTALL_BINARY: 0
      - run: yarn run packages:test:ci

  required-frontend-unit-tests:
    needs:
      - frontend-unit-tests
      - frontend-decoupled-plugin-tests
      - frontend-packages-unit-tests
    if: always()
    name: All frontend unit tests complete
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Check test suites
        uses: ./.github/actions/check-jobs
        with:
          needs: ${{ toJson(needs) }}
          failure-message: One or more frontend test jobs failed
          success-message: All frontend test jobs completed successfully
